[database]
#Golbat Database settings
username = "user"
password = "password"
host = "127.0.0.1"
port = "3306"
name = "golbatdbname"

[discord]
#Discord bot token
token = ""
#channel IDs for Discord that you want the boards posted to, array support infinite channels
channelIDs = ["yourchannelid","moarchannelids"] 

[discord.emojis]
#can be any unicode emojis or custom discord emojis using the full identifier eg :emoij:12345678910 or <:emoji12345678910>
valor = "ğŸ”´"
mystic = "ğŸ”µ"
instinct = "ğŸŒ•"
uncontested = "âšªï¸"
normal = "ğŸ£"
glacial = "â„ï¸"
mossy = "ğŸŒ¿"
magnetic = "ğŸ§²"
rainy = "ğŸ’§"
sparkly = "ğŸ…"
scanned = "ğŸ“ˆ"
hundo = "ğŸ’¯"
nundo = "ğŸ—‘ï¸"
shinies = "âœ¨"
grunt = "ğŸ¥‰"
leader = "ğŸ¥ˆ"
giovanni = "ğŸ¥‡"
kecleon = "ğŸŸ¢"
showcase = "ğŸ†"
route = "â›³ï¸"
level1 = "1ï¸âƒ£"
level3 = "3ï¸âƒ£"
level4 = "4ï¸âƒ£"
level5 = "5ï¸âƒ£"
mega = "ğŸ“£"
elite = "ğŸ²"

[api]
#golbat url and port
url = "http://127.0.0.1:9001"
#golbat secret
secret = "secret"

#coordinates below define the area in which API calls are made - adjust if needed for multi-instances where you only want to show active counts for a certain area, defaults cover the world
[coordinates.min]
latitude = -90
longitude = -180

[coordinates.max]
latitude = 90
longitude = 180

[config]
#refresh time in seconds that the board will query the db
refreshInterval = 60
#if set to false active counts will be removed from hundos/nundos and API calls won't be made
includeActiveCounts = true 
#Title of the embed
EmbedTitle = "Today's PokÃ©mon Stats"
