[database]
#Golbat Database settings
username = "user"
password = "password"
host = "127.0.0.1"
port = "3306"
name = "golbatdbname"

[discord]
#Discord bot token
token = ""
#channel IDs for Discord that you want the boards posted to, array support infinite channels
channelIDs = ["yourchannelid","moarchannelids"]

[level_emoji]
"1" = "1ï¸âƒ£"
"3" = "3ï¸âƒ£"
"4" = "4ï¸âƒ£"
"5" = "5ï¸âƒ£"
"6" = "ğŸ“£"
"9" = "ğŸ²"
"11" = "âš«"
"13" = "âš«"

[reward_emoji]
"2" = "ğŸ›’"
"3" = "ğŸŒŸ"
"7" = "ğŸ˜ˆ"
"12" = "âš¡ï¸"

[lure_emoji]
"501" = "ğŸ£"
"502" = "â„ï¸"
"503" = "ğŸŒ¿"
"504" = "ğŸ§²"
"505" = "ğŸ’§"
"506" = "ğŸ…"

[rocket_emoji]
"1" = "ğŸ¥‰"
"2" = "ğŸ¥ˆ"
"3" = "ğŸ¥‡"

[event_emoji]
"8" = "ğŸŸ¢"
"9" = "ğŸ†"

[api]
#golbat url and port
url = "http://127.0.0.1:9001"
#golbat secret leave blank if not used
secret = ""

#coordinates below define the area in which API calls are made - adjust if needed for multi-instances where you only want to show active counts for a certain area, defaults cover the world
[coordinates.min]
latitude = -90
longitude = -180

[coordinates.max]
latitude = 90
longitude = 180

[config]
#refresh time in seconds that the board will query the db
refreshInterval = 60
errorRefreshInterval = 30
#if set to false active counts will be removed from hundos/nundos and API calls won't be made
includeActiveCounts = true 
#Title of the embed
EmbedTitle = "Today's PokÃ©mon Stats"
